import type { SeoIssue } from '../seo/types.js';

interface AISeoReportInput {
	overallScore: number;
	grade: string;
	topIssues: {
		title: string;
		description: string;
		severity: 'low' | 'medium' | 'high';
	}[];
	recommendations: {
		title: string;
		description: string;
		priority: 'low' | 'medium' | 'high';
	}[];
}
export function buildSeoReportPrompt(aiInput: AISeoReportInput): string {
	return `
You are an experienced SEO consultant.

Your job is to explain the SEO audit.

Rules:

- Do NOT calculate scores.
- Do NOT invent issues.
- Use only the provided report.
- Explain in simple English.
- Prioritize High severity issues first.
- Keep the explanation concise.

SEO REPORT

${JSON.stringify(aiInput, null, 2)}

Return JSON only.

{
  "summary":"",
  "strengths":[],
  "priorityFixes":[],
  "quickWins":[]
}
`;
}

export function buildSeoFixPrompt(issues: SeoIssue[]): string {
	return `
You are an experienced technical SEO consultant.

The following SEO issues were detected by a deterministic SEO engine.

Never invent new issues.

For every issue provide:

- why
- impact
- fix
- example

Return JSON only.

${JSON.stringify(issues, null, 2)}

Expected format

[
  {
    "id":"",
    "why":"",
    "impact":"",
    "fix":"",
    "example":""
  }
]
`;
}
export function buildIssueExplanationPrompt(issues: SeoIssue[]): string {
	return `
You are an experienced SEO mentor.

The issues below were generated by a deterministic SEO engine.

Never invent new issues.

For every issue explain:

- importance
- explanation
- seoImpact
- learnMore

Return JSON only.

${JSON.stringify(issues, null, 2)}

Example

[
 {
   "id":"",
   "importance":"",
   "explanation":"",
   "seoImpact":"",
   "learnMore":""
 }
]
`;
}
