import type { SeoIssue, SeoReport } from '../seo/types.js';

interface AISeoReportInput {
	overallScore: number;
	grade: string;
	topIssues: {
		title: string;
		description: string;
		severity: 'low' | 'medium' | 'high';
	}[];
	recommendations: {
		title: string;
		description: string;
		priority: 'low' | 'medium' | 'high';
	}[];
}
export function buildSeoReportPrompt(aiInput: AISeoReportInput): string {
	return `
You are an experienced SEO consultant.

Your job is to explain the SEO audit.

Rules:

- Do NOT calculate scores.
- Do NOT invent issues.
- Use only the provided report.
- Explain in simple English.
- Prioritize High severity issues first.
- Keep the explanation concise.

SEO REPORT

${JSON.stringify(aiInput, null, 2)}

Return JSON only.

{
  "summary":"",
  "strengths":[],
  "priorityFixes":[],
  "quickWins":[]
}
`;
}

export function buildSeoFixPrompt(issues: SeoIssue[]): string {
	return `
You are an experienced technical SEO consultant.

The following SEO issues were detected by a deterministic SEO engine.

Never invent new issues.

For every issue provide:

- why
- impact
- fix
- example

Return JSON only.

${JSON.stringify(issues, null, 2)}

Expected format

[
  {
    "id":"",
    "why":"",
    "impact":"",
    "fix":"",
    "example":""
  }
]
`;
}
export function buildIssueExplanationPrompt(issues: SeoIssue[]): string {
	return `
You are an experienced SEO mentor.

The issues below were generated by a deterministic SEO engine.

Never invent new issues.

For every issue explain:

- importance
- explanation
- seoImpact
- learnMore

Return JSON only.

${JSON.stringify(issues, null, 2)}

Example

[
 {
   "id":"",
   "importance":"",
   "explanation":"",
   "seoImpact":"",
   "learnMore":""
 }
]
`;
}

export function buildOptimizationPlanPrompt(report: SeoReport): string {
	const aiInput = {
		overallScore: report.overallScore,

		grade: report.grade,

		topIssues: report.issues.slice(0, 10),

		recommendations: report.recommendations.slice(0, 10),
	};

	return `
You are an experienced SEO consultant.

The following report was produced by a deterministic SEO engine.

Never invent issues.

Create a prioritized optimization plan.

Rules

- Highest priority first.
- Explain expected benefit.
- Keep explanations practical.
- Mention estimated difficulty.
- Mention estimated SEO impact.

Return JSON only.

${JSON.stringify(aiInput, null, 2)}

Expected format

{
 "summary":"",
 "priorityFixes":[

   {

     "priority":1,

     "title":"",

     "reason":"",

     "difficulty":"Easy",

     "impact":"High"

   }

 ],

 "quickWins":[],

 "strengths":[]

}
`;
}

interface MetaGenerationInput {
	url: string;
	currentTitle: string;
	currentMetaDescription: string;
	report: SeoReport;
}

export function buildMetaGenerationPrompt(input: MetaGenerationInput): string {
	const aiInput = {
		url: input.url,
		currentTitle: input.currentTitle,
		currentMetaDescription: input.currentMetaDescription,
		score: input.report.overallScore,
		topIssues: input.report.issues.slice(0, 5),
	};

	return `
You are an experienced SEO specialist.

Improve the title and meta description.

Rules:

- Do not invent page content.
- Keep the original intent.
- Title: 50-60 characters.
- Description: 140-160 characters.
- Include the primary keyword naturally.
- Return JSON only.

${JSON.stringify(aiInput, null, 2)}

Expected format:

{
	"title":"",
	"description":"",
	"reason":""
}
`;
}

interface HeadingGenerationInput {
	url: string;
	currentTitle: string;
	currentHeadings: { level: number; text: string }[];
	report: SeoReport;
}

export function buildHeadingGenerationPrompt(
	input: HeadingGenerationInput,
): string {
	const aiInput = {
		url: input.url,
		title: input.currentTitle,
		headings: input.currentHeadings,
		score: input.report.overallScore,
		topIssues: input.report.issues
			.filter((issue) => issue.id.startsWith('HEADING'))
			.slice(0, 5),
	};

	return `
You are an SEO content strategist.

Improve the heading hierarchy.

Rules:

- Preserve page intent.
- One H1 only.
- Logical H2 structure.
- H3 only under H2.
- Don't invent unrelated sections.
- Return JSON only.

${JSON.stringify(aiInput, null, 2)}

Expected JSON

{
  "h1":"",
  "h2":[
    {
      "title":"",
      "children":[]
    }
  ],
  "reason":""
}
`;
}
