export const SEO_SECTION_SCORE = {
	TITLE: 15,
	META: 15,
	URL: 5,
	HEADING: 10,
	IMAGE: 10,
	LINK: 10,
	TECHNICAL: 15,
	SCHEMA: 5,
	OPEN_GRAPH: 5,
	TWITTER: 5,
	ACCESSIBILITY: 10,
	PERFORMANCE: 10,
	CANONICAL:5
} as const;
